# Generated by Django 4.2.2 on 2023-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingmartapp', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='noted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=20)),
                ('option', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='notesFiles')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
