# Generated by Django 4.2.2 on 2023-07-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingmartapp', '0003_noted'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.BigIntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='note',
        ),
    ]
